# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest 

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '6.x'
    checkLatest: true  

- task: Npm@1
  inputs:
    command: 'install'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snyk'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: false 

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'prajktamhapsekar829'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'prajktamhapsekar829'
    cliProjectName: 'facebook-socialmedia'
    cliSources: '.'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'